apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: witchat-doppler
  namespace: witchat
spec:
  tokenSecret:
    name: doppler-token-secret
  managedSecret:
    name: witchat-managed
    type: Opaque
  project: witchat
  config: dev
  resyncSeconds: 60
