apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: witchat

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - doppler-secret.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: witchat

images:
  - name: 192.168.1.247:8080/witchat/app
    newTag: latest
